### ISSUE TITLE
"USB device not recognized" Windows error Code 43 when library used with Arduino Nano

### ISSUE THREAD

**Issue by Hogar665** [todd-herbert/unoHID#1] opened 2023-08-12 10:46 UTC
Hello,

I am trying to make a small portable mouse jiggler with this library but am facing the issue with Arduino Nano being recognized as a mouse or anything at all when pugged in.
I tested this with Uno board as well and its working perfectly but not with Nano.

I tried to read USB-IDs-for-free.txt to understand how usb_descriptor.h works but I really don't understand a thing from there.
There aren't much resources about this on Arduino forums or anywhere else so I decided to write here for help.

I assume something needs to be tweaked in usb_descriptor.h in order for this board to be recognized but as I said I don't understand how it works.

Hope this reaches someone who is working on the project and any help or direction on how to solve this will be much appriciated.
Thanks in advance!

**Comment by todd-herbert** [comment] 2023-08-12 15:44
>I tested this with Uno board as well and its working perfectly but not with Nano.
That's very interesting.. 

I don't have a nano to test it unfortunately, but as it supposedly also uses ATmega328, I would have expected it to work!

I should double check, that you are definitely using a "Nano", and not "Nano Every", "Nano 33 BLE", "Nano 33 BLE SENSE", "Nano 33 IOT", "Nano RP2040 Connect", or other variant?

> I assume something needs to be tweaked in usb_descriptor.h in order for this board to be recognized
I don't think this will be the case. The descriptor describes the "keyboard and mouse" to the host machine. There is no specific information there about the Arduino itself.

I'm really not sure what the cause of this issue is. Starting with the basics, do you think you could share some close-up pictures of your setup: the Nano and the V-USB wiring?

I am interested in solving this: I will order a Nano to investigate, but that could take a while.

**Comment by Hogar665** [comment] 2023-08-12 16:28
Hello Todd,

Thanks a lot for writing back.
I am using a Chinese clone of an Arduino Nano but I am pretty sure it has ATmega328P as it says on a chip.
I made a small board size of a a tump drive with rest of the components and USB A connector but I am sure that everything works fine with it become I tested it with Arduino Uno and it worked perfectly.

Thanks again for taking interest in solving this.
If you still need some pictures of my setup let me know.

If there is something I can find out from a serial monitor that can help you guess the cause maybe let me know as well.
I am also opened to idea to try troubleshooting this together on some private chat room or something and then post the results here for everyone else.

**Comment by todd-herbert** [comment] 2023-08-12 16:57
>I am using a Chinese clone of an Arduino Nano

This would possibly be my best guess at the problem so far. I have personally had a few odd experiences with mislabeled chips before, so it's not impossible.

> If you still need some pictures of my setup let me know.
 * You wiring was tested working with the Uno
 * You are using a classic Nano.
 * Your Nano is a clone.
 
 I think this is pretty much all that pictures would have investigated, so probably no need right now.
 
___

It might be an idea to write a sketch confirming pins 2, 4, and 5 are working correctly as digital inputs and outputs.

Another idea would be to poke around in [usbconfig.h](https://github.com/todd-herbert/unoHID/blob/main/src/vusb/driver/usbconfig.h). Changing the pins *might* help something, but you have to be sure to change the other settings in the file to match. 
* Pin 2 could only be move to Pin 3, and you would have to adjust the "Optional MCU Description" section at the end of usbconfig.h. I have never experimented with this.

* Pins 4 and 5 could be changed for any pin 0 to 7, without needing to further rearrange the code.
 
___

I suspect it will be ~2 weeks before the Nano I ordered arrives. At that point I will be able to confirm for you whether the issue is related to the clone or not.

If you make any progress on the issue before then, let me know! I'm not sure what other help I can be right now, but if you have any questions, feel free to ask.

**Comment by todd-herbert** [comment] 2023-08-12 17:07
After-thoughts: 
* [UsbTreeView](https://www.google.com/search?client=firefox-b-d&q=usbtreeview) can be helpful in investigating USB issues.
* If you haven't already, try [manual polling](https://github.com/todd-herbert/unoHID#timers)
* You could try adjust the timings in the [`VUSBController::begin()`](https://github.com/todd-herbert/unoHID/blob/main/src/vusb/vusb_controller.cpp) method

**Comment by todd-herbert** [comment] 2023-08-29 14:43
I have tested with a genuine Arduino Nano today, and I can confirm that there is some strange behaviour.

@Hogar665 Would you be able to check for me whether the issues are resolved by running the sketch on your nano while the IDE serial monitor is open?

**Comment by todd-herbert** [comment] 2023-08-30 09:10
@Hogar665 Looking underneath your Nano clone, is the USB IC FT232 or CH340?

**Comment by todd-herbert** [comment] 2023-08-30 09:29
I am not sure if the issue I have noticed with the genuine Nano is the same as the issue you faced.
They may be different, but related:

In certain conditions, Arduino Nano fails to begin USB connection.
    On my setup, the issue occurs only when *all* of these conditions are met:

* Board is Arduino Nano
* The Nano's on-board "Mini-B USB connection" is connected to a Windows PC
* The Nano's serial port is **not** open on the Windows PC (serial monitor)

The exact cause is still unknown, but after a lot of experimenting, it seems to be an issue with the Windows driver for the Nano's USB serial adapter. This issue has a handful of reports over the years, however it doesn't seem acknowledged by the Arduino community.

The computer's driver seems to reset the virtual COM port, which triggers the Nano's USB Serial IC to send the DTR signal, which resets the ATmega328P. On my setup, this issue can be prevented by holding the Nano's reset pin HIGH.

To make this action as easy as possible, I have added a workaround:
```cpp
#define PIN_KEEPALIVE 6
#include "unoHID.h"

// Continue as normal
void setup() {
    Keyboard.begin();
}
```
Define `PIN_KEEPALIVE` however you like, then connect the pin directly to RST.
Sketch upload should still work as normal; the pin is only held HIGH during crucial setup moments.

**Comment by Hogar665** [comment] 2023-09-01 07:35
Hello todd,

Sorry for not being responsive these day I have been busy.
Thanks for looking into this without me ill try your workaround and let you know if it works.

USB IC on my board is CH340C

**Comment by Hogar665** [comment] 2023-09-01 08:21
I just tried adding PIN_KEEPALIVE and got some errors in IDE:

In file included from C:\Users\Username\AppData\Local\Temp\.arduinoIDE-unsaved202381-12048-zeqiyw.4qdjg\sketch_sep1a\sketch_sep1a.ino:2:0:
C:\Users\Username\Documents\Arduino\libraries\unoHID\src/unoHID.h:19:25: note: #pragma message: Connect RST pin to PIN_KEEPALIVE
         #pragma message "Connect RST pin to PIN_KEEPALIVE"

Also I don't believe I understood you what I have to do for this workaround.
Do I have to connect some pins on the arduino board or should PIN_KEEPALIVE 6 work with the sketch that you made with the default pins?

**Comment by todd-herbert** [comment] 2023-09-02 14:11
> Sorry for not being responsive these day I have been busy.

No need for sorry! I wouldn't have been surprised if you had simply moved on with your project.

> USB IC on my board is CH340C

Hmm, it could be a different issue than the one I faced, but still worth a try with the workaround.

>I just tried adding PIN_KEEPALIVE and got some errors in IDE:

Ah, sorry, that isn't an error, just a reminder to do the physical wiring part.
It's probably not clear enough. I may need to reword the message.

> Also I don't believe I understood you what I have to do for this workaround.

Two steps:
* `#define PIN_KEEPALIVE 6` at the top of your code
* Connect a wire between pin 6, and the reset pin on your nano

![connection](https://github.com/todd-herbert/unoHID/assets/24772776/c6ec9367-63ad-4b76-840a-75db23eaf0eb)

It doesn't need to be pin 6, any pin should work.

Seeing how your Nano has a different USB Serial chip, I do doubt whether this workaround will help, but please, give it a go and let me know the result!

**Comment by todd-herbert** [comment] 2023-09-20 00:35
@Hogar665 
I have now tested the library using a generic Nano clone, which has a CH340 USB Serial IC.
I have not been able to replicate the issue you mentioned. With the clone, everything seems to work fine.

It is worth noting, that with a genuine Nano, I *did* see a similar issue to the one you mentioned. 
In my case, this was fixed by `#define PIN_KEEPALIVE 6`, and connecting pin 6 directly to pin RST.
Did you ever manage to try this out?

**Closed as not planned** 2024-01-07 00:37 UTC
Labels: question, unreproducible
